apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: bytag-mirror
spec:
  imageTagMirrors:
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/openshift4/ose-cli
      source: registry.redhat.io/openshift4/ose-cli
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/qt/doctrain/simulation_doctrain
      source: nexus.alm.oncite.io/docker/qt/doctrain/simulation_doctrain
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/keycloak/keycloak
      source: nexus.alm.oncite.io/docker/keycloak/keycloak
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/apache-kafka-operator/amq-streams/bridge-rhel9
      source: nexus.alm.oncite.io/docker/products/operators/apache-kafka-operator/amq-streams/bridge-rhel9
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/apache-kafka-operator/amq-streams/kafka-38-rhel9
      source: nexus.alm.oncite.io/docker/products/operators/apache-kafka-operator/amq-streams/kafka-38-rhel9
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/apache-kafka-operator/amq-streams/kafka-39-rhel9
      source: nexus.alm.oncite.io/docker/products/operators/apache-kafka-operator/amq-streams/kafka-39-rhel9
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/apache-kafka-operator/amq-streams/maven-builder-rhel9
      source: nexus.alm.oncite.io/docker/products/operators/apache-kafka-operator/amq-streams/maven-builder-rhel9
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/apache-kafka-operator/amq-streams/strimzi-rhel9-operator
      source: nexus.alm.oncite.io/docker/products/operators/apache-kafka-operator/amq-streams/strimzi-rhel9-operator
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgadmin4
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgadmin4
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgbackrest
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgbackrest
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgbouncer
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-pgbouncer
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-exporter
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-exporter
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres-gis
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-postgres
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-upgrade
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/crunchy-upgrade
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/crunchy-postgres-operator/crunchydata/postgres-operator
      source: nexus.alm.oncite.io/docker/products/operators/crunchy-postgres-operator/crunchydata/postgres-operator
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/keycloak-operator
      source: nexus.alm.oncite.io/docker/products/operators/keycloak-operator
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/operators/keycloak-providers/providers-image
      source: nexus.alm.oncite.io/docker/products/operators/keycloak-providers/providers-image
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/tools/images/gec-ubi
      source: nexus.alm.oncite.io/docker/tools/images/gec-ubi
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/tools/k6/k6doctrain
      source: nexus.alm.oncite.io/docker/tools/k6/k6doctrain
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/eclipse-mosquitto
      source: nexus.alm.oncite.io/docker/eclipse-mosquitto
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/oauth2-proxy/oauth2-proxy
      source: nexus.alm.oncite.io/docker/oauth2-proxy/oauth2-proxy
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/oauth2-proxy/oauth2-proxy
      source: nexus.alm.oncite.io/docker/oauth2-proxy/oauth2-proxy
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-alloy
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-alloy
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-ingress
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-ingress
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-loki
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-loki
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-observability
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-observability
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-onlinehelp
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-onlinehelp
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/dps-portal
      source: nexus.alm.oncite.io/docker/products/oncite-dps/dps-portal
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/hmi/hmi-client
      source: nexus.alm.oncite.io/docker/products/oncite-dps/hmi/hmi-client
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-address-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-address-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-attribute-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-attribute-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-configuration-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-configuration-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-dashboard-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-dashboard-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-idgenerator-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-idgenerator-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-kpi-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-kpi-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-kpi-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-kpi-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-machinedata-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-machinedata-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-masterdata-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-masterdata-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-masterdata-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-masterdata-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-portal-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-portal-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-productionview-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-productionview-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-shiftplan-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-shiftplan-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-smartmom-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-smartmom-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-storage-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-storage-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-storage-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-storage-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-testplan-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-testplan-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-transactiondata-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-transactiondata-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-transfer-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-transfer-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/smartmom-suite/smom-usermanagement-ui
      source: nexus.alm.oncite.io/docker/products/oncite-dps/smartmom-suite/smom-usermanagement-ui
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/sse-mqtt-bridge
      source: nexus.alm.oncite.io/docker/products/oncite-dps/sse-mqtt-bridge
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/virtual-factory/frontends/vf-ui-frontend
      source: nexus.alm.oncite.io/docker/products/oncite-dps/virtual-factory/frontends/vf-ui-frontend
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/virtual-factory/services/vf-asset-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/virtual-factory/services/vf-asset-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/virtual-factory/services/vf-core-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/virtual-factory/services/vf-core-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/products/oncite-dps/virtual-factory/services/vf-smartmom-service
      source: nexus.alm.oncite.io/docker/products/oncite-dps/virtual-factory/services/vf-smartmom-service
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/tools/images/gec-ubi
      source: nexus.alm.oncite.io/docker/tools/images/gec-ubi
    - mirrors:
      - registry-oc-mirror.apps.ipc4.sps2025.com/docker/tools/images/gec-ubi
      source: nexus.alm.oncite.io/docker/tools/images/gec-ubi
