---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntp-config
data:
  chrony.conf: |
    pool 0.pool.ntp.org iburst
    pool 1.pool.ntp.org iburst
    pool 2.pool.ntp.org iburst
    driftfile /var/lib/chrony/drift
    rtcsync
    makestep 1.0 3
    allow 192.168.100.0/24
