FROM quay.io/centos/centos:stream9

LABEL maintainer="sps-2025"
LABEL name="ntp-chrony"

# Install chrony
RUN dnf -y update && \
    dnf -y install chrony && \
    dnf clean all && \
    rm -rf /var/cache/dnf /var/cache/yum

# Default config path is /etc/chrony.conf; when used with the DaemonSet
# we mount the ConfigMap to that path.

EXPOSE 123/udp

STOPSIGNAL SIGTERM

CMD ["chronyd", "-f", "/etc/chrony.conf", "-n"]
