---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-router-certs-global
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["router-certs-default"]
    verbs: ["get", "list", "watch"]