---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apply-acp-standard-services
  namespace: openshift-gitops
rules:
  - apiGroups: ["", "apps", "argoproj.io"]
    resources: ["secrets", "applications"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["config.openshift.io"]
    resources: ["clusteroperators"]
    verbs: ["get", "list", "watch"]