---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-mirror-configmap
data: 
  imagesetconfiguration.yaml: |
    ---
    kind: ImageSetConfiguration
    apiVersion: mirror.openshift.io/v1alpha2
    archiveSize: 4
    storageConfig:
      registry:
        imageURL: registry.oc-mirror.svc.cluster.local:5000/mirror/oc-mirror-metadata
        skipTLS: true
    mirror:
      platform:
        graph: true
        channels:
          - name: stable-4.20
            type: ocp
            minVersion: 4.20.15
            maxVersion: 4.20.15
      operators:
        - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
          packages:
            - name: ansible-automation-platform-operator
              channels:
                - name: stable-2.6
                  minVersion: 'aap-operator.v2.6.0-0.1772556720'
                  maxVersion: 'aap-operator.v2.6.0-0.1772556720'
            - name: kubernetes-nmstate-operator
              channels:
                - name: stable
            - name: kubevirt-hyperconverged
              channels:
                - name: stable
            - name: lvms-operator
              channels:
                - name: stable-4.20
            - name: openshift-gitops-operator
              channels:
                - name: latest
                  minVersion: 'openshift-gitops-operator.v1.19.2'
                  maxVersion: 'openshift-gitops-operator.v1.19.2'
        - catalog: quay.io/rhpds/gitea-catalog:v2.1.0
          packages:
            - name: gitea-operator
              channels:
                - name: stable
      additionalImages:
        - name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:a17ebe09a69f28a183068c3597467311ba9ed77f1c3a42864404d5e343f7c2de
        - name: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:8b51f6026000a9f63e8d548e5d4c7b630425bc4504819ceeef97eea691653cd2
        - name: quay.io/luferrar/sps@sha256:986b04077494891165caf55010eca39a3352d58ecd336be1cf7ad4f1d7c4515b
        - name: registry.redhat.io/openshift4/ose-cli@sha256:69762925e16053d77685ff3a08b3b45dd2bfa5d68277851bc6969b368bbd0cb9
        # CustomerEnvironment_cmf-sps-demo-agent
        - name: criticalmanufacturing.io/3rd-party/traefik:3.5.2
        - name: criticalmanufacturing.io/customerportal/edge-forward-proxy:11.2.0
        - name: criticalmanufacturing.io/customerportal/edge-squid-proxy:11.2.0
        # CustomerEnvironment_cmf-sps-demo-ms-environment
        - name: criticalmanufacturing.io/3rd-party/ch-ui:20250613-unofficial
        - name: criticalmanufacturing.io/3rd-party/clickhouse-server:25.3.3.42
        - name: criticalmanufacturing.io/3rd-party/cp-kafka:7.6.2-1-ubi8
        - name: criticalmanufacturing.io/3rd-party/kafka-ui:v0.7.2
        - name: criticalmanufacturing.io/3rd-party/minio:2024.7.31
        - name: criticalmanufacturing.io/3rd-party/rabbitmq:3.13.7-management-alpine
        - name: criticalmanufacturing.io/3rd-party/traefik:3.6.2
        - name: criticalmanufacturing.io/criticalmanufacturing/automationmanagercontroller:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/discoveryservices:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/envmanager:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/grafana:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/help:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/host:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/ioteventprocessor:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/lbogenerator:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/mcad:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/mes-scheduler:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/mes-ui:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/messagebus:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/rasa-actions:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/rasa:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/reference:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/securityportal:11.2.5
        - name: criticalmanufacturing.io/criticalmanufacturing/traefik-forwardauth:11.2.5
        - name: criticalmanufacturing.io/dataplatform/aggregationengine:11.2.5
        - name: criticalmanufacturing.io/dataplatform/cube:11.2.5
        - name: criticalmanufacturing.io/dataplatform/cubestore:11.2.5
        - name: criticalmanufacturing.io/dataplatform/datamanager:11.2.5
        - name: criticalmanufacturing.io/dataplatform/epf-alarm-management-action-trigger:11.2.5
        - name: criticalmanufacturing.io/dataplatform/epf-alarm-management-event-rule-handler:11.2.5
        - name: criticalmanufacturing.io/dataplatform/epf-alarm-management-mes-event-handler:11.2.5
        - name: criticalmanufacturing.io/dataplatform/housekeeper:11.2.5
        - name: criticalmanufacturing.io/dataplatform/mlplatformagent:11.2.5
        - name: criticalmanufacturing.io/dataplatform/mlplatformtraining:11.2.5
        - name: criticalmanufacturing.io/dataplatform/redis:11.2.5
        # GermanEdgeCloud VM Microshift images
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:80819f88795a16b1df3cea66b7fe57d68b504b08fcbaaf245716f3caed588e82
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c9f0041b0290be2d1e0f96f6727c3a70071105d6a83890e0a5503e9f77da8529
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8f714fb9046c1842f044c5c074486baf5ce3ea05db479b5624702cd5f2f45a99
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6fa6e5b1fabb9b7165ee4928637b9b28c5966d7f192d4866c7453c2149ef1376
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fc87935eb676a73b877cca295ccae2502645c3183a416363c9dcf9be6cf2c08f
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:89dd57ce21c549ec2260cb5ac317482d7523789cce340ce16be13c4a9fa41a16
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6d84b5c4e89d3e9920d29dbb4e6220d7711ee8e35b6f712afb48d9d237331322
        - name: registry.redhat.io/lvms4/lvms-rhel9-operator@sha256:58804d8baf922927b66cec9424d431a3bdb341d207024ce40cc8f0123bac03ee
        - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1cba2314e3276572ca1f179bc0b27a5f496865f7762f641a4bc87c4a4597018b
