---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  labels:
    app.kubernetes.io/name: registry-pvc
    app.kubernetes.io/part-of: bootstrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-mirror-scratch-pvc
  labels:
    app.kubernetes.io/name: oc-mirror-scratch-pvc
    app.kubernetes.io/part-of: bootstrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi