FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

ARG OC_VERSION=4.19.0

LABEL maintainer="sps-2025"
LABEL name="run-oc-mirror"

# Install runtime deps
RUN microdnf -y update && \
    microdnf -y install curl tar gzip jq skopeo ca-certificates which podman wget && \
    microdnf clean all && rm -rf /var/cache/dnf /var/cache/yum

# Download OpenShift `oc` client
RUN set -eux; \
    OC_TAR_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OC_VERSION}/openshift-client-linux-${OC_VERSION}.tar.gz"; \
    echo "Downloading oc from ${OC_TAR_URL}"; \
    wget "${OC_TAR_URL}" -O openshift-client-linux.tar.gz &&\
    tar xzvf openshift-client-linux.tar.gz -C /usr/bin/ &&\
    chmod +x /usr/bin/oc &&\
    rm -fr openshift-client-linux.tar.gz &&\
    mkdir -p /root/.docker

# Copy oc-mirror binary (release tarball expected)
COPY oc-mirror /usr/bin/oc-mirror
RUN chmod +x /usr/bin/oc-mirror

# Add entrypoint script
COPY run-oc-mirror.sh /usr/local/bin/run-oc-mirror.sh
RUN chmod +x /usr/local/bin/run-oc-mirror.sh

WORKDIR /tmp

ENTRYPOINT ["/usr/local/bin/run-oc-mirror.sh"]
