FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as python-base

RUN microdnf install python3 python3-pip openssh-clients -y && \
    microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /var/log/{dnf,yum}

FROM python-base as ansible-base

RUN mkdir /tmp/{pip,wheels}
ADD ansible.txt /tmp/pip/ansible.txt
WORKDIR /tmp/pip
RUN python3 -m pip wheel --wheel-dir=/tmp/wheels -r ansible.txt

FROM ansible-base as ansible-galaxy

RUN microdnf install findutils krb5-devel gcc python3-devel git -y && \
    microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /var/log/{dnf,yum}

RUN python3 -m pip install --no-cache-dir ansible-core ansible-builder

RUN mkdir -p /tmp/ansible/{roles,collections}

ADD ansible.cfg /tmp/ansible/ansible.cfg
ADD requirements.yml /tmp/ansible/requirements.yml
ADD requirements.txt /tmp/pip/requirements.txt

WORKDIR /tmp/ansible
RUN ansible-galaxy collection install -r requirements.yml --collections-path /tmp/ansible/collections
RUN ansible-builder introspect --sanitize /tmp/ansible/collections | sed -n '/^python:/,/^system:/{/^-/{s/^- *'\''//;s/'\''//;s/ *#.*//;s/;.*//;p}}' | { grep -v 'kafka-python-ng\|systemd-python' || :; } > /tmp/pip/pip-install.txt

WORKDIR /tmp/pip
RUN python3 -m pip wheel --no-cache-dir --wheel-dir=/tmp/wheels -r pip-install.txt

FROM ansible-base as execution-environment

RUN mkdir /usr/share/ansible

COPY --from=ansible-galaxy /tmp/ansible/collections /usr/share/ansible/collections
COPY --from=ansible-base /tmp/pip/ansible.txt /tmp/pip/ansible.txt
COPY --from=ansible-base /tmp/wheels /tmp/wheels
COPY --from=ansible-galaxy /tmp/pip/pip-install.txt /tmp/pip/pip-install.txt
COPY --from=ansible-galaxy /tmp/wheels /tmp/wheels
WORKDIR /tmp/pip
RUN python -m pip install --no-index --no-cache-dir --find-links=/tmp/wheels -r ansible.txt -r pip-install.txt
RUN rm -rf /tmp/wheels /tmp/ansible.txt /tmp/pip-install.txt

RUN mkdir -p /runner/{playbooks,inventory,variables}

WORKDIR /runner
LABEL ansible-execution-environment=true
USER 1000

CMD ["bash"]
