apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  ports:
  - port: 1883
  selector:
    app: mqtt-broker
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pv-claim
  namespace: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  selector:
    matchLabels:
      app: mqtt-broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - image: eclipse-mosquitto:latest
          name: mosquitto
          ports:
          - containerPort: 1883
            name: mosquitto
          volumeMounts:
          - name: mosquitto-persistent-storage
            mountPath: /mosquitto/data
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      volumes:
      - name: mosquitto-persistent-storage
        persistentVolumeClaim:
          claimName: mq-pv-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config