apiVersion: v1
kind: Namespace
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    argocd.argoproj.io/managed-by: openshift-gitops