---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
  - namespace.yaml
  - configmap.yaml
  - job.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml

